name: patrol_basics_tutorial
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.15
  flutter_timezone: ^3.0.1
  permission_handler: ^11.3.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  patrol: ^3.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/

patrol:
  app_name: Patrol Basics Tutorial
  android:
    package_name: com.resocoder.patrol_basics_tutorial
  ios:
    bundle_id: com.resocoder.patrolBasicsTutorial
